### ISSUE TITLE
Not able to host the on github pages

### ISSUE THREAD

**Issue by therajanmaurya** [amitmerchant1990/reverie#26]
I tried using `Use this template` but not able to host on github pages. 

Here is my instance: https://therajanmaurya.github.io/

Getting this 
![image](https://user-images.githubusercontent.com/5724482/79069133-6d3a8f80-7ce9-11ea-9b48-457f99e682db.png)

**Comment by amitmerchant1990** [comment]
You'll need to update following parameters in `_config.yml` file according to your needs.

```yml
# Your website URL (e.g. http://amitmerchant1990.github.io or http://www.amitmerchant.com)
# Used for Sitemap.xml and your RSS feed
url: http://www.amitmerchant.com/reverie
enforce_ssl: https://www.amitmerchant.com/reverie

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: "/reverie"
```
