### ISSUE TITLE
Collection post won't show up in categories

### ISSUE THREAD

**Issue by Gabriel-p** [amitmerchant1990/reverie#80]
The `Categories` page works fine for posts in the `_posts` folder, but my posts in a collection I created will not show there. The collection's folder is called `_clusters`, I modified the `_config.yml` file as shown below but it will not work

```
include: ['_pages', '_clusters']

collections:
  clusters:
    output: true
```

Any help will be much appreciated
